<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<div class="flex gap-2 items-center tooltip ml-auto"
     x-data="{ tooltipVisible: false }"
     role="tooltip">
    <div x-on:mouseenter.self="tooltipVisible = true"
         x-on:mouseleave.self="tooltipVisible = false"
         x-on:click.outside.away="tooltipVisible = false"
         x-on:click="tooltipVisible = !tooltipVisible"
         class="relative hover:cursor-pointer">
        <?= $heroicons->questionMarkCircleHtml('w-7 h-7 opacity-75 hover:opacity-100 icon', 24, 24, ['title' => __('More information')]) ?>
        <template x-if="tooltipVisible">
            <div class="absolute -right-3 px-3 pt-3 w-80 z-10">
                <div class="shadow-lg px-3 py-2 bg-gray-500 relative text-white rounded-md text-sm">
                    <div class="h-3 w-3 bg-gray-500 rotate-45 transform origin-bottom-left absolute right-3 -top-3"></div>
                    <?= $escaper->escapeHtml($block->getText()) ?>
                </div>
            </div>
        </template>
    </div>
</div>