<?php 

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Pricing\Helper\Data as CurrencyHelper;
use Hyva\HyvaShippingDhl\Magewire\NoNeighbor;
use Hyva\HyvaShippingDhl\ViewModel\Tooltip;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var NoNeighbor $magewire */
/** @var Tooltip $tooltip */
/** @var CurrencyHelper $currency */
$tooltip = $viewModels->require(Tooltip::class);
$currency = $this->helper(CurrencyHelper::class);
$feenote = __('This service will incur additional shipping costs of $1 including VAT.')->render();
$feenote = str_replace('$1', $currency->currency($magewire->fee, true, false), $feenote);
?>
<div class="mb-6">
    <h4 class="font-bold my-3"><?= $escaper->escapeHtml(__('No Neighbor Delivery: Discreet Dispatch')) ?></h4>
    <div class="flex md:items-center">
        <div class="flex">
            <input wire:model="noNeighbor"
                   x-data="{ disabled: $wire.entangle('disabled') }"
                   type="checkbox"
                   id="noNeighbor"
                   class="field checkbox w-4 h-4 renderer-checkbox cursor-pointer"
                   :class="disabled ? 'disabled:opacity-50' : ''"
                   x-bind:disabled="disabled"
                   wire:click="$emitTo('checkout.shipping.method.dhlpaket_bestway_preferred_neighbor', 'refresh')"
            />
        </div>
        <label class="mb-0 ml-4" for="noNeighbor">
            <span class="hover:cursor-pointer text-base">
                <?= $escaper->escapeHtml(__('Use No Neighbour Delivery Service')) ?>
            </span>
        </label>

        <?= $tooltip->render(__('Exclude an alternative delivery to the neighbor if you are not available when the delivery is made.')) ?>
    </div>
    <p><?= $escaper->escapeHtml($feenote); ?></p>
</div>
